### ISSUE TITLE
可否提交给golang，方便更多的人使用到您的成果？

### ISSUE THREAD

**Issue by it512** [emmansun/base64#4]

**Comment by emmansun** [comment]
感谢您的建议，其实Go已经有类似的PR: https://github.com/golang/go/issues/20206 ，不过Go Team从可维护性等角度出发，对功能性模块进行asm汇编优化不是很推荐。况且本项目也是刚创建不久，需要更多用户反馈及相应优化。

**Comment by it512** [comment]
谢谢！
